apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: first-trigger
spec:
  broker: first-broker
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: my-service
    uri: /sample_path
