#apiVersion: v1
#kind: Service
#metadata:
#  name: logger-loadbalancer
#spec:
#  selector:
#    app: logger
#  ports:
#    - port: 8081
#      targetPort: 80
#  type: LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: my-broker-service
spec:
  selector:
    eventing.knative.dev/broker: broker1
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: my-broker-specific-configuration
  namespace: default
data:
  channel-template-spec: |
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel

---

apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: MTChannelBasedBroker
  name: broker1
spec:
  # Configuration specific to this broker.
  config:
    apiVersion: v1
    kind: ConfigMap
    name: my-broker-specific-configuration
    namespace: default

---

apiVersion: v1
kind: Service
metadata:
  name: forwarding-service
spec:
  selector:
    app: logger
  ports:
    - port: 8082
      targetPort: 80

---

apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: triger1
spec:
  broker: broker1
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: forwarding-service

#---
#
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: logger-deployment
#  labels:
#    app: logger
#spec:
#  replicas: 2
#  selector:
#    matchLabels:
#      app: logger
#  template:
#    metadata:
#      labels:
#        app: logger
#    spec:
#      containers:
#        - name: logger
#          image: chlebq/mgr:0.0.1
#          ports:
#            - containerPort: 80

---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: logger
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: chlebq/mgr:0.0.1
          ports:
            - containerPort: 80 # Port to route to