apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: first-role
  namespace: api-server-source
rules:
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - get
    - list
    - watch
